# Generated by Django 6.0 on 2025-12-18 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='impact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.impact'),
        ),
    ]
