# Generated by Django 5.2.8 on 2025-12-11 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Standard User'), ('IT_SUPPORT', 'IT Support Team'), ('ADMIN', 'Administrator')], default='USER', max_length=15),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_FEEDBACK', 'Resolved - Awaiting User Feedback'), ('REOPENED', 'Reopened by User'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_satisfied', models.BooleanField(choices=[(True, 'Yes (Satisfied)'), (False, 'No (Not Satisfied/Reopen)')], default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('provided_at', models.DateTimeField(auto_now_add=True)),
                ('provided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_history', to='accounts.incident')),
            ],
            options={
                'verbose_name_plural': 'Ticket Feedback',
                'ordering': ['-provided_at'],
            },
        ),
    ]
