# Generated by Django 6.0 on 2025-12-18 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='subsidiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subsidiary'),
        ),
    ]
