# Generated by Django 5.2.8 on 2025-12-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_role_alter_incident_status_ticketfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='resolved_on',
            new_name='resolved_date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolved_time',
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
