# Generated by Django 6.0 on 2025-12-18 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_incident_subsidiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_action', models.BooleanField(default=False)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('resolved_time', models.TimeField(blank=True, null=True)),
                ('delays', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='accounts.incident')),
            ],
        ),
    ]
