# Generated by Django 5.2.8 on 2025-12-08 11:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_category_subcategory_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='incidents/', validators=[accounts.models.validate_file_extension]),
        ),
    ]
