# Generated by Django 6.0 on 2025-12-19 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_incidenttracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('catID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subcategory')),
            ],
        ),
    ]
