# Generated by Django 6.0 on 2025-12-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_by', models.CharField(max_length=100)),
                ('login_date', models.DateField(auto_now_add=True)),
                ('login_time', models.TimeField(auto_now_add=True)),
                ('logout_date', models.DateField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
