# Generated by Django 6.0 on 2025-12-19 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_loginmonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='In Use', max_length=100)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField()),
                ('software_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_audit_date', models.DateField()),
                ('admin_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category')),
                ('custodian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SLAManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_due', models.DateTimeField()),
                ('resolution_due', models.DateTimeField()),
                ('responded_on', models.DateTimeField(blank=True, null=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('sla_status', models.CharField(default='Within SLA', max_length=50)),
                ('breach_reason', models.TextField(blank=True, null=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='accounts.incident')),
            ],
        ),
    ]
