# Generated by Django 5.2.8 on 2025-12-09 09:29

import datetime # <-- ADDED IMPORT FOR datetime module
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employee_dept_alter_employee_discipline_and_more'),
    ]

    operations = [
        # --- Category Model Fixes ---
        migrations.AddField(
            model_name='category',
            name='active',
            # default=True is correct, no change needed as it's the model default
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='created_on',
            # FIXED: Changed invalid '00:00:00' to a valid Python date object
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 1, 1)), 
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='created_time',
            # FIXED: Changed invalid timezone.now to a valid time string
            field=models.TimeField(auto_now_add=True, default='00:00:00'), 
            preserve_default=False,
        ),
        
        # --- SubCategory Model Fixes ---
        migrations.AddField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_on',
            # FIXED: Changed invalid timezone.now to a valid Python date object
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_time',
            # FIXED: Changed invalid timezone.now to a valid time string
            field=models.TimeField(auto_now_add=True, default='00:00:00'),
            preserve_default=False,
        ),
        
        # --- Existing Operations ---
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='subsidiary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]