# Generated by Django 6.0 on 2025-12-19 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_asset_slamanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCauseCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='software_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RcSubcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('rc_catID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rootcausecat')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Closed'), ('in_progress', 'In Progress')], default='open', max_length=20)),
                ('known_issue', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('resolved_time', models.TimeField(blank=True, null=True)),
                ('delays', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problems', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('root_cause_subCatID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rcsubcat')),
                ('root_cause_catID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rootcausecat')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('freq_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('detected_on', models.DateField(blank=True, null=True)),
                ('threshold_limit', models.IntegerField(default=5)),
                ('time_window_hours', models.IntegerField(default=24)),
                ('rc_catID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rootcausecat')),
            ],
        ),
    ]
