# Generated by Django 6.0 on 2025-12-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rootcausecat_alter_asset_software_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(max_length=100)),
                ('storage_location', models.CharField(max_length=100)),
                ('last_success_date', models.DateField(blank=True, null=True)),
                ('next_schedule', models.DateField()),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.asset')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=100)),
                ('status', models.CharField(default='Detected', max_length=50)),
                ('detected_on', models.DateField(auto_now_add=True)),
                ('detected_time', models.TimeField(auto_now_add=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('resolved_time', models.TimeField(blank=True, null=True)),
                ('affected_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.asset')),
                ('assigned_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('support_email', models.EmailField(max_length=100)),
                ('support_phone', models.CharField(max_length=100)),
                ('sla_agreement', models.TextField(max_length=500)),
                ('contract_expiry', models.DateField()),
                ('account_number', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('asset_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category')),
            ],
        ),
    ]
