# Generated by Django 6.0 on 2025-12-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auditmanagement_backupmanagement_securitymanagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='rc_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rootcausecat'),
        ),
    ]
